[workspace]
authors = ["Neko Ayaka <neko@ayaka.moe>"]
channels = ["conda-forge"]
name = "env"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
pip = ">=25.2,<26"

[target.linux-64.dependencies]
cuda = ">=13.0.2,<14"
cuda-cupti = ">=13.0.85,<14"
cuda-libraries-dev = ">=13.0.2,<14"
cuda-nvcc = ">=13.0.88,<14"
cuda-nvtx = ">=13.0.85,<14"

[target.linux-64.pypi-dependencies]
torch = { version = ">=2.9.0, <3", index = "https://download.pytorch.org/whl/cu130" }
torchvision = { version = ">=0.24.0, <0.25", index = "https://download.pytorch.org/whl/cu130" }

[pypi-dependencies]
onnx = ">=1.19.1, <2"
onnxslim = ">=0.1.72, <0.2"
onnxruntime = ">=1.23.2, <2"
optimum-onnx = { version = ">=0.0.3, <0.0.4", extras = ["onnxruntime"] }
